# Generated by Django 3.1.2 on 2020-10-04 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_categorias_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocorrencias',
            name='estado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='API.estados'),
        ),
    ]
