# Generated by Django 3.1.2 on 2020-10-04 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_auto_20201004_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocorrencias',
            name='data_atualizacao',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='ocorrencias',
            name='data_criacao',
            field=models.DateField(auto_now_add=True),
        ),
    ]
